[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
auto_savings = "V1YHSMC6Utp5smG67DL1vvPstcsAik6YSCFSJkfN79q"

[programs.localnet]
auto_savings = "8AZGuEtnmaqT97sMeF2zUAnv5J89iXCBVPnxw5fULzoS"

[programs.mainnet]
auto_savings = "V1YHSMC6Utp5smG67DL1vvPstcsAik6YSCFSJkfN79q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
